# Generated by Django 4.1.7 on 2023-03-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_img', models.ImageField(upload_to='')),
                ('project_link', models.URLField()),
            ],
        ),
    ]
